-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 22:50:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jobsitedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobsitedb` ;

-- -----------------------------------------------------
-- Schema jobsitedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobsitedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jobsitedb` ;

-- -----------------------------------------------------
-- Table `jobsitedb`.`candidatejobapplied`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`candidatejobapplied` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`candidatejobapplied` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `JobID` INT(11) NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  `ApplyDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_JobCandidate_JobID`
    FOREIGN KEY (`JobID`)
    REFERENCES `jobsitedb`.`job` (`Id`),
  CONSTRAINT `FK_JobCandidate_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `jobsitedb`.`user` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_JobCandidate_UserID_idx` ON `jobsitedb`.`candidatejobapplied` (`UserID` ASC) VISIBLE;

CREATE INDEX `FK_JobCandidate_JobID_idx` ON `jobsitedb`.`candidatejobapplied` (`JobID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`candidateskills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`candidateskills` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`candidateskills` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` INT(11) NULL DEFAULT NULL,
  `SkillID` INT(11) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_CandidateSkills_SkillID`
    FOREIGN KEY (`SkillID`)
    REFERENCES `jobsitedb`.`skillset` (`Id`),
  CONSTRAINT `FK_CandidateSkills_User_Id`
    FOREIGN KEY (`UserID`)
    REFERENCES `jobsitedb`.`user` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';

CREATE INDEX `FK_CandidateSkills_User_Id_idx` ON `jobsitedb`.`candidateskills` (`UserID` ASC) VISIBLE;

CREATE INDEX `FK_CandidateSkills_SkillID_idx` ON `jobsitedb`.`candidateskills` (`SkillID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`companyinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`companyinfo` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`companyinfo` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(45) NULL DEFAULT NULL,
  `BusinessPhone` VARCHAR(45) NULL DEFAULT NULL,
  `WebSite` VARCHAR(45) NULL DEFAULT NULL,
  `CompanyImage` VARCHAR(45) NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_CompanyInfo_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `jobsitedb`.`user` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';

CREATE INDEX `FK_UserID_Company_User_ID_idx` ON `jobsitedb`.`companyinfo` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`job` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`job` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `JobDescription` VARCHAR(45) NULL DEFAULT NULL,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  `JobCategoryID` INT(11) NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  `StartDate` DATETIME NULL DEFAULT NULL,
  `EndDate` DATETIME NULL DEFAULT NULL,
  `IsActive` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_JobPost_Category_Id`
    FOREIGN KEY (`JobCategoryID`)
    REFERENCES `jobsitedb`.`jobcategory` (`Id`),
  CONSTRAINT `FK_JobPost_User_ID`
    FOREIGN KEY (`UserID`)
    REFERENCES `jobsitedb`.`user` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_JobPost_User_ID_idx` ON `jobsitedb`.`job` (`UserID` ASC) VISIBLE;

CREATE INDEX `FK_JobPost_Category_Id_idx` ON `jobsitedb`.`job` (`JobCategoryID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`jobcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`jobcategory` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`jobcategory` (
  `Id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` INT(11) NULL DEFAULT NULL,
  `CreateDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';


-- -----------------------------------------------------
-- Table `jobsitedb`.`skillset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`skillset` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`skillset` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jobsitedb`.`skillsforjob`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`skillsforjob` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`skillsforjob` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `SkillID` INT(11) NULL DEFAULT NULL,
  `JobID` INT(11) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_SkillForJob_JobId`
    FOREIGN KEY (`JobID`)
    REFERENCES `jobsitedb`.`job` (`Id`),
  CONSTRAINT `FK_SkillForJob_SkillId`
    FOREIGN KEY (`SkillID`)
    REFERENCES `jobsitedb`.`skillset` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_SkillForJob_JobId_idx` ON `jobsitedb`.`skillsforjob` (`JobID` ASC) VISIBLE;

CREATE INDEX `FK_SkillForJob_SkillId_idx` ON `jobsitedb`.`skillsforjob` (`SkillID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`user` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`user` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` TINYINT(4) NULL DEFAULT NULL,
  `IsLocked` TINYINT(4) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `ModifiedDate` DATETIME NOT NULL,
  `UserTypeID` INT(11) NULL DEFAULT NULL,
  `CreateDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `CreatedDate`, `ModifiedDate`),
  CONSTRAINT `User_UserTypeID_UserType_UID`
    FOREIGN KEY (`UserTypeID`)
    REFERENCES `jobsitedb`.`usertype` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `UID_idx` ON `jobsitedb`.`user` (`UserTypeID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`userprofilestate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`userprofilestate` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`userprofilestate` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IsEmailSent` TINYINT(4) NULL DEFAULT NULL,
  `IsSmsSent` TINYINT(4) NULL DEFAULT NULL,
  `PasswordResetGuid` VARCHAR(255) NULL DEFAULT NULL,
  `PasswordResetExpiryGuid` DATETIME NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `ModifiedDate` DATETIME NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_UserProfile_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `jobsitedb`.`user` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '	';

CREATE INDEX `FK_UserProfile_UserID_idx` ON `jobsitedb`.`userprofilestate` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jobsitedb`.`usertype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobsitedb`.`usertype` ;

CREATE TABLE IF NOT EXISTS `jobsitedb`.`usertype` (
  `Id` INT(11) NOT NULL,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
